vich_uploader:
    db_driver: orm
    mappings:
        menu_images:
            uri_prefix: /uploads/menus
            upload_destination: '%kernel.project_dir%/public/uploads/menus'
            namer: Vich\UploaderBundle\Naming\UniqidNamer